# Generated by Django 4.2.11 on 2024-04-29 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="session",
        ),
    ]
